CREATE TABLE If Not EXISTS SERVICE (
     ID SERIAL PRIMARY KEY,
     NAME VARCHAR NOT NULL,
     VALUE_PROPOSITION VARCHAR,
     BIZ_CAPACITY VARCHAR,
     CREATE_TIME timestamp NOT NULL,
     UPDATE_TIME timestamp,
     DOMAIN_ID SERIAL REFERENCES DOMAIN (ID)
 )